# Generated by Django 4.2.17 on 2026-01-15 12:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_house_term_remove_newsandevents_summary_ru_and_more"),
        (
            "accounts",
            "0003_student_house_user_is_class_teacher_user_is_teacher_and_more",
        ),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_level",
                    models.CharField(
                        choices=[
                            ("Primary 1", "Primary 1"),
                            ("Primary 2", "Primary 2"),
                            ("Primary 3", "Primary 3"),
                            ("Primary 4", "Primary 4"),
                            ("Primary 5", "Primary 5"),
                            ("Primary 6", "Primary 6"),
                            ("JHS 1", "JHS 1"),
                            ("JHS 2", "JHS 2"),
                            ("JHS 3", "JHS 3"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("First", "First Term"),
                            ("Second", "Second Term"),
                            ("Third", "Third Term"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tuition_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "pta_dues",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Parent-Teacher Association dues",
                        max_digits=10,
                    ),
                ),
                (
                    "sports_levy",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "exam_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "library_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "development_levy",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "other_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.session"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Structure",
                "verbose_name_plural": "Fee Structures",
                "ordering": ["session", "term", "grade_level"],
                "unique_together": {("grade_level", "term", "session")},
            },
        ),
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            (
                                "Mobile Money",
                                "Mobile Money (MTN, Vodafone, AirtelTigo)",
                            ),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cheque", "Cheque"),
                        ],
                        default="Cash",
                        max_length=50,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Mobile Money ref or transaction ID",
                        max_length=100,
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.feestructure",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.session"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="accounts.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.term"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Payment",
                "verbose_name_plural": "Student Payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
