# Generated by Django 4.2.17 on 2026-01-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
        ("payments", "0003_alter_feestructure_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feestructure",
            options={
                "ordering": ["year", "term", "grade_level"],
                "verbose_name": "Fee Structure",
                "verbose_name_plural": "Fee Structures",
            },
        ),
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="studentpayment",
            name="session",
        ),
        migrations.AddField(
            model_name="feestructure",
            name="year",
            field=models.CharField(
                default="2024", help_text="Academic year (e.g., 2024)", max_length=4
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feestructure",
            unique_together={("grade_level", "term", "year", "school")},
        ),
        migrations.RemoveField(
            model_name="feestructure",
            name="session",
        ),
    ]
