# Generated by Django 4.2.17 on 2026-02-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_feestructure_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructure",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("Nursery 1", "Nursery 1"),
                    ("Nursery 2", "Nursery 2"),
                    ("KG 1", "KG 1"),
                    ("KG 2", "KG 2"),
                    ("Primary 1", "Primary 1"),
                    ("Primary 2", "Primary 2"),
                    ("Primary 3", "Primary 3"),
                    ("Primary 4", "Primary 4"),
                    ("Primary 5", "Primary 5"),
                    ("Primary 6", "Primary 6"),
                    ("JHS 1", "JHS 1"),
                    ("JHS 2", "JHS 2"),
                    ("JHS 3", "JHS 3"),
                ],
                max_length=20,
            ),
        ),
    ]
