# Generated by Django 4.2.17 on 2026-01-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_newsandevents_summary_es_newsandevents_summary_fr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("points", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("First", "First Term"),
                            ("Second", "Second Term"),
                            ("Third", "Third Term"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "is_current_term",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("next_term_begins", models.DateField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.session",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="summary_ru",
        ),
        migrations.RemoveField(
            model_name="newsandevents",
            name="title_ru",
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="summary_ee",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="summary_ga",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="summary_tw",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="title_ee",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="title_ga",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="title_tw",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="Semester",
        ),
    ]
