# Generated by Django 4.2.17 on 2026-01-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('core', '0004_house_term_remove_newsandevents_summary_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='house',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='session',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='term',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('name', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('session', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('term', 'session', 'school')},
        ),
    ]
