# Generated by Django 4.2.17 on 2026-01-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
        ("core", "0005_activitylog_school_house_school_newsandevents_school_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="session",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="session",
            name="school",
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="term",
            name="year",
            field=models.CharField(
                default="2024", help_text="Academic year (e.g., 2024)", max_length=4
            ),
        ),
        migrations.AlterUniqueTogether(
            name="term",
            unique_together={("term", "year", "school")},
        ),
        migrations.RemoveField(
            model_name="term",
            name="session",
        ),
    ]
