# Generated by Django 4.2.17 on 2026-01-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_session_unique_together_remove_session_school_and_more"),
        ("attendance", "0003_alter_attendancesummary_unique_together_and_more"),
        ("payments", "0004_alter_feestructure_options_and_more"),
        ("course", "0007_remove_courseallocation_session"),
        ("result", "0005_remove_becemockexam_session_becemockexam_year"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Session",
        ),
    ]
