# Generated by Django 4.2.17 on 2026-02-13 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_term_result_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='specific_users',
            field=models.ManyToManyField(blank=True, help_text="Send to specific individuals (Overrides division/role if 'Specific Users' role is selected)", related_name='targeted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='target_division',
            field=models.CharField(blank=True, choices=[('Nursery', 'Nursery/Pre-School'), ('Primary', 'Primary School'), ('JHS', 'Junior High School')], help_text='Send to all users in this division (Leave empty for all divisions)', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='target_role',
            field=models.CharField(choices=[('ALL', 'All Roles'), ('TEACHERS', 'Teachers'), ('STUDENTS', 'Students'), ('PARENTS', 'Parents'), ('SPECIFIC', 'Specific Users')], default='ALL', help_text='Target a specific role within the division', max_length=20),
        ),
    ]
