# Generated by Django 4.2.17 on 2026-02-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newsandevents_specific_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(blank=True, help_text='Term end date', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(blank=True, help_text='Term start date', null=True),
        ),
    ]
