# Generated by Django 4.2.17 on 2026-01-15 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0004_alter_course_code_alter_course_credit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="course",
            name="summary_ru",
        ),
        migrations.RemoveField(
            model_name="course",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="course",
            name="year",
        ),
        migrations.RemoveField(
            model_name="courseallocation",
            name="lecturer",
        ),
        migrations.RemoveField(
            model_name="program",
            name="summary_ru",
        ),
        migrations.RemoveField(
            model_name="program",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="summary_ru",
        ),
        migrations.RemoveField(
            model_name="uploadvideo",
            name="title_ru",
        ),
        migrations.AddField(
            model_name="course",
            name="is_core_subject",
            field=models.BooleanField(
                default=True, help_text="Core subjects are mandatory"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="summary_ee",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="summary_ga",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="summary_tw",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="term",
            field=models.CharField(
                choices=[
                    ("First", "First Term"),
                    ("Second", "Second Term"),
                    ("Third", "Third Term"),
                ],
                default="First",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="title_ee",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_ga",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_tw",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="courseallocation",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocated_teacher",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="program",
            name="summary_ee",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="summary_ga",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="summary_tw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_ee",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_ga",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_tw",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="title_ee",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="title_ga",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="title_tw",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="summary_ee",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="summary_ga",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="summary_tw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="title_ee",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="title_ga",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="title_tw",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Primary 1", "Primary 1"),
                    ("Primary 2", "Primary 2"),
                    ("Primary 3", "Primary 3"),
                    ("Primary 4", "Primary 4"),
                    ("Primary 5", "Primary 5"),
                    ("Primary 6", "Primary 6"),
                    ("JHS 1", "JHS 1"),
                    ("JHS 2", "JHS 2"),
                    ("JHS 3", "JHS 3"),
                ],
                max_length=25,
            ),
        ),
    ]
