# Generated by Django 4.2.17 on 2026-01-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('course', '0005_remove_course_credit_remove_course_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='program',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_ee',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_es',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_ga',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title_tw',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('title', 'school')},
        ),
    ]
