# Generated by Django 4.2.17 on 2026-01-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_course_school_program_school_alter_course_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseallocation",
            name="session",
        ),
    ]
