# Generated by Django 4.2.17 on 2026-02-09 12:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_term_result_released"),
        ("course", "0007_remove_courseallocation_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Nursery 1", "Nursery 1"),
                    ("Nursery 2", "Nursery 2"),
                    ("KG 1", "KG 1"),
                    ("KG 2", "KG 2"),
                    ("Primary 1", "Primary 1"),
                    ("Primary 2", "Primary 2"),
                    ("Primary 3", "Primary 3"),
                    ("Primary 4", "Primary 4"),
                    ("Primary 5", "Primary 5"),
                    ("Primary 6", "Primary 6"),
                    ("JHS 1", "JHS 1"),
                    ("JHS 2", "JHS 2"),
                    ("JHS 3", "JHS 3"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="LessonNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.PositiveIntegerField(
                        help_text="Week number for this lesson (e.g., Week 1, Week 2)",
                        verbose_name="Week Number",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Lesson Title"),
                ),
                (
                    "topic",
                    models.CharField(
                        max_length=300, verbose_name="Topic/Subject Matter"
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        help_text="What students should learn/achieve by the end of the lesson",
                        verbose_name="Learning Objectives",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Detailed lesson content and key points to cover",
                        verbose_name="Lesson Content",
                    ),
                ),
                (
                    "methodology",
                    models.TextField(
                        help_text="Teaching methods, activities, and instructional strategies",
                        verbose_name="Teaching Methods",
                    ),
                ),
                (
                    "assessment",
                    models.TextField(
                        blank=True,
                        help_text="How student learning will be assessed",
                        verbose_name="Assessment Methods",
                    ),
                ),
                (
                    "resources_needed",
                    models.TextField(
                        blank=True,
                        help_text="Materials, equipment, and resources needed",
                        verbose_name="Resources/Materials",
                    ),
                ),
                (
                    "homework",
                    models.TextField(
                        blank=True,
                        help_text="Homework or assignments for students",
                        verbose_name="Homework/Assignment",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional: Attach supporting documents (PDF, DOCX, DOC)",
                        null=True,
                        upload_to="lesson_notes/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docx", "doc"]
                            )
                        ],
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Needs Revision"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "admin_comments",
                    models.TextField(
                        blank=True,
                        help_text="Feedback from admin/reviewer",
                        verbose_name="Admin Comments",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_lesson_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Teacher",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.term",
                        verbose_name="Term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Note",
                "verbose_name_plural": "Lesson Notes",
                "ordering": ["-created_at"],
                "unique_together": {("course", "term", "week_number", "teacher")},
            },
        ),
    ]
