# Generated by Django 4.2.17 on 2026-02-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_custom_domain_school_is_active_and_more'),
        ('course', '0008_alter_course_level_lessonnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='division',
            field=models.CharField(blank=True, choices=[('Nursery', 'Nursery/Pre-School'), ('Primary', 'Primary School'), ('JHS', 'Junior High School')], help_text='Academic division this program belongs to', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_academic_block',
            field=models.BooleanField(default=True, help_text='True for main academic divisions (Nursery, Primary, JHS), False for subject departments'),
        ),
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Subject name, e.g., English Language, Mathematics', max_length=200)),
                ('code_prefix', models.CharField(help_text='Subject code prefix, e.g., ENG, MATH, SCI', max_length=50)),
                ('level', models.CharField(choices=[('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('KG 1', 'KG 1'), ('KG 2', 'KG 2'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3')], help_text='Grade level for this subject', max_length=25)),
                ('division', models.CharField(choices=[('Nursery', 'Nursery/Pre-School'), ('Primary', 'Primary School'), ('JHS', 'Junior High School')], help_text='Academic division', max_length=25)),
                ('is_core_subject', models.BooleanField(default=True, help_text='Core subjects are mandatory for all students')),
                ('is_elective', models.BooleanField(default=False, help_text='Elective subjects are optional')),
                ('description', models.TextField(blank=True, help_text='Brief description of the subject content and objectives')),
                ('school', models.ForeignKey(blank=True, help_text='School this template belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name': 'Subject Template',
                'verbose_name_plural': 'Subject Templates',
                'ordering': ['division', 'level', 'title'],
                'unique_together': {('code_prefix', 'level', 'school')},
            },
        ),
    ]
