# Generated by Django 4.2.17 on 2026-02-03 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_term_result_released"),
        ("accounts", "0006_user_department"),
        ("school", "0002_school_custom_domain_school_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Tuition Fee, Exam Fee", max_length=100
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Primary 1", "Primary 1"),
                            ("Primary 2", "Primary 2"),
                            ("Primary 3", "Primary 3"),
                            ("Primary 4", "Primary 4"),
                            ("Primary 5", "Primary 5"),
                            ("Primary 6", "Primary 6"),
                            ("JHS 1", "JHS 1"),
                            ("JHS 2", "JHS 2"),
                            ("JHS 3", "JHS 3"),
                        ],
                        help_text="Leave blank for all levels",
                        max_length=25,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("First", "First Term"),
                            ("Second", "Second Term"),
                            ("Third", "Third Term"),
                        ],
                        help_text="Leave blank for all terms",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="school.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Structure",
                "verbose_name_plural": "Fee Structures",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentFeeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Can override default fee amount",
                        max_digits=10,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fee_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fees.feestructure",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_assignments",
                        to="accounts.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.term"
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Fee Assignment",
                "verbose_name_plural": "Student Fee Assignments",
                "ordering": ["-created_at"],
                "unique_together": {("student", "fee_structure", "term")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "Paystack (Online)"),
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("MOBILE_MONEY", "Mobile Money"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Verification"),
                            ("VERIFIED", "Verified"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "paystack_reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "paystack_data",
                    models.JSONField(
                        blank=True, help_text="Raw Paystack response", null=True
                    ),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("payment_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to specific fee assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="fees.studentfeeassignment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="school.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
