# Generated by Django 4.2.17 on 2026-02-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_school_custom_domain_school_is_active_and_more"),
        ("accounts", "0006_user_department"),
        ("fees", "0002_alter_feestructure_amount_feeitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank Account"),
                            ("MOBILE_MONEY", "Mobile Money"),
                        ],
                        default="BANK",
                        max_length=20,
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, help_text="e.g., GCB Bank, Ecobank", max_length=100
                    ),
                ),
                (
                    "account_name",
                    models.CharField(help_text="Account holder name", max_length=150),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, help_text="Bank account number", max_length=50
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True, help_text="Bank branch name", max_length=100
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        blank=True,
                        help_text="For international transfers",
                        max_length=20,
                    ),
                ),
                (
                    "mobile_money_number",
                    models.CharField(
                        blank=True, help_text="Mobile Money number", max_length=20
                    ),
                ),
                (
                    "mobile_money_network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MTN", "MTN Mobile Money"),
                            ("VODAFONE", "Vodafone Cash"),
                            ("AIRTELTIGO", "AirtelTigo Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Primary account displayed to students"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional instructions for students"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Bank Account",
                "verbose_name_plural": "School Bank Accounts",
                "ordering": ["-is_default", "-is_active", "account_type"],
            },
        ),
        migrations.CreateModel(
            name="StudentPaymentReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        editable=False,
                        help_text="Unique payment reference code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="QR code for payment reference",
                        null=True,
                        upload_to="payment_qr_codes/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Student Payment Reference",
                "verbose_name_plural": "Student Payment References",
            },
        ),
        migrations.AddField(
            model_name="feestructure",
            name="auto_assign",
            field=models.BooleanField(
                default=True,
                help_text="Automatically assign this fee to all students in the specified level/term",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_type",
            field=models.CharField(
                default="MANUAL",
                help_text="Payment gateway used (MANUAL, HUBTEL, etc.)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student", "status"], name="fees_paymen_student_a03bf9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="fees_paymen_payment_1bd5e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["school", "status", "payment_date"],
                name="fees_paymen_school__b51c02_idx",
            ),
        ),
        migrations.AddField(
            model_name="studentpaymentreference",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_reference",
                to="accounts.student",
            ),
        ),
        migrations.AddField(
            model_name="schoolbankaccount",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="school.school",
            ),
        ),
    ]
