# Generated by Django 4.2.17 on 2026-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="custom_domain",
            field=models.URLField(
                blank=True, help_text="Custom domain for this school", null=True
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="school",
            name="primary_color",
            field=models.CharField(
                default="#007bff", help_text="Primary theme color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="secondary_color",
            field=models.CharField(
                default="#6c757d", help_text="Secondary theme color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="subdomain",
            field=models.SlugField(
                default=1,
                help_text="Subdomain for this school",
                max_length=200,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
