# Generated by Django 4.2.17 on 2026-02-23 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_school_custom_domain_school_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="accent_color",
            field=models.CharField(
                default="#ffc107",
                help_text="Accent / highlight color (hex)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="founded_year",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Year the school was founded", null=True
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="motto",
            field=models.CharField(
                blank=True,
                help_text="School motto or tagline",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="secondary_logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional secondary logo / crest",
                null=True,
                upload_to="school_logos/",
                verbose_name="School Crest",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="primary_color",
            field=models.CharField(
                default="#007bff", help_text="Primary theme color (hex)", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="secondary_color",
            field=models.CharField(
                default="#6c757d", help_text="Secondary theme color (hex)", max_length=7
            ),
        ),
        migrations.CreateModel(
            name="PromotionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotion_cut_off",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Students scoring >= this average are automatically promoted.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Promotion Cut-Off (%)",
                    ),
                ),
                (
                    "failure_cut_off",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="Students scoring < this average automatically fail/repeat. Students between failure and promotion cut-offs are 'Borderline' (require review).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Failure Cut-Off (%)",
                    ),
                ),
                (
                    "apply_to_all_terms",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, promotion is evaluated at the end of every term. Otherwise only at the end of the academic year (last term).",
                        verbose_name="Apply Each Term",
                    ),
                ),
                (
                    "allow_teacher_requests",
                    models.BooleanField(
                        default=True,
                        help_text="Teachers can submit promotion exception requests for borderline/failed students.",
                        verbose_name="Allow Teacher Promotion Requests",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_policy",
                        to="school.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Policy",
                "verbose_name_plural": "Promotion Policies",
            },
        ),
        migrations.CreateModel(
            name="GradeWeightConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_classwork",
                    models.BooleanField(default=True, verbose_name="Use Classwork"),
                ),
                (
                    "use_class_test",
                    models.BooleanField(
                        default=True, verbose_name="Use Class Test / Mid-Sem"
                    ),
                ),
                (
                    "use_assignment",
                    models.BooleanField(default=True, verbose_name="Use Assignment"),
                ),
                (
                    "use_attendance",
                    models.BooleanField(default=False, verbose_name="Use Attendance"),
                ),
                (
                    "use_project",
                    models.BooleanField(default=False, verbose_name="Use Project"),
                ),
                (
                    "classwork_weight",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Classwork Weight (%)",
                    ),
                ),
                (
                    "class_test_weight",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Class Test / Mid-Sem Weight (%)",
                    ),
                ),
                (
                    "assignment_weight",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Assignment Weight (%)",
                    ),
                ),
                (
                    "attendance_weight",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Attendance Weight (%)",
                    ),
                ),
                (
                    "project_weight",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Project Weight (%)",
                    ),
                ),
                (
                    "exam_weight",
                    models.PositiveSmallIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="End of Term Exam Weight (%)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_config",
                        to="school.school",
                        verbose_name="School",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Weight Configuration",
                "verbose_name_plural": "Grade Weight Configurations",
            },
        ),
    ]
