# Generated by Django 4.2.17 on 2026-01-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_essayquestion_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="choice_text_ru",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_ru",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="title_ru",
        ),
        migrations.AddField(
            model_name="choice",
            name="choice_text_ee",
            field=models.CharField(
                help_text="Enter the choice text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="choice_text_ga",
            field=models.CharField(
                help_text="Enter the choice text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="choice_text_tw",
            field=models.CharField(
                help_text="Enter the choice text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content_ee",
            field=models.CharField(
                help_text="Enter the question text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content_ga",
            field=models.CharField(
                help_text="Enter the question text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content_tw",
            field=models.CharField(
                help_text="Enter the question text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_ee",
            field=models.TextField(
                blank=True,
                help_text="Explanation to be shown after the question has been answered.",
                max_length=2000,
                null=True,
                verbose_name="Explanation",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_ga",
            field=models.TextField(
                blank=True,
                help_text="Explanation to be shown after the question has been answered.",
                max_length=2000,
                null=True,
                verbose_name="Explanation",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_tw",
            field=models.TextField(
                blank=True,
                help_text="Explanation to be shown after the question has been answered.",
                max_length=2000,
                null=True,
                verbose_name="Explanation",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_ee",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the quiz",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_ga",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the quiz",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_tw",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the quiz",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title_ee",
            field=models.CharField(max_length=60, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title_ga",
            field=models.CharField(max_length=60, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title_tw",
            field=models.CharField(max_length=60, null=True, verbose_name="Title"),
        ),
    ]
