# Generated by Django 4.2.17 on 2026-02-16 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_remove_choice_choice_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment title', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text='Assignment instructions and requirements', verbose_name='Description')),
                ('file', models.FileField(blank=True, help_text='Optional: Upload assignment document (PDF, DOCX, etc.)', null=True, upload_to='assignments/%Y/%m/%d/', verbose_name='Assignment File')),
                ('due_date', models.DateTimeField(help_text='Submission deadline', verbose_name='Due Date')),
                ('max_score', models.IntegerField(default=100, help_text='Maximum points for this assignment', verbose_name='Maximum Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='FillInTheBlankQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('correct_answer', models.CharField(help_text='The correct answer text', max_length=200, verbose_name='Correct Answer')),
                ('case_sensitive', models.BooleanField(default=False, help_text='Should the answer be case-sensitive?', verbose_name='Case Sensitive')),
            ],
            options={
                'verbose_name': 'Fill in the Blank Question',
                'verbose_name_plural': 'Fill in the Blank Questions',
            },
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.question')),
                ('correct_answer', models.BooleanField(help_text='Is the correct answer True or False?', verbose_name='Correct Answer')),
            ],
            options={
                'verbose_name': 'True/False Question',
                'verbose_name_plural': 'True/False Questions',
            },
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(help_text='Upload your assignment file', upload_to='assignment_submissions/%Y/%m/%d/', verbose_name='Submitted File')),
                ('submission_text', models.TextField(blank=True, help_text='Optional: Add notes or explanation', verbose_name='Submission Text')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Score awarded by teacher', max_digits=5, null=True, verbose_name='Grade')),
                ('feedback', models.TextField(blank=True, help_text='Comments from the teacher', verbose_name='Teacher Feedback')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.assignment', verbose_name='Assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Graded By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submission_date'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
