# Generated by Django 4.2.17 on 2026-02-16 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_assignment_fillintheblankquestion_truefalsequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_review_after_submission',
            field=models.BooleanField(default=True, help_text='Students can review their answers after submitting', verbose_name='Allow Review After Submission'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Quiz becomes available to students at this date/time', null=True, verbose_name='Available From'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Quiz is no longer available after this date/time', null=True, verbose_name='Available Until'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_correct_answers_after',
            field=models.DateTimeField(blank=True, help_text='Correct answers will be visible after this date/time', null=True, verbose_name='Show Correct Answers After'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes for completing the quiz. Leave blank for unlimited time.', null=True, verbose_name='Time Limit (minutes)'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='auto_submit_on_timeout',
            field=models.BooleanField(default=True, help_text='Automatically submit when time expires', verbose_name='Auto Submit on Timeout'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='time_remaining_seconds',
            field=models.IntegerField(blank=True, help_text='Remaining time in seconds for timed quizzes', null=True, verbose_name='Time Remaining (seconds)'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='time_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time Started'),
            preserve_default=False,
        ),
    ]
