# Generated by Django 4.2.17 on 2026-02-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_quiz_allow_review_after_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="max_attempts",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 attempt (default)"),
                    (2, "2 attempts"),
                    (3, "3 attempts"),
                    (4, "4 attempts"),
                    (5, "5 attempts"),
                ],
                default=1,
                help_text="Maximum number of attempts a student can make. When more than 1, the highest score is recorded for reports.",
                verbose_name="Max Attempts",
            ),
        ),
        migrations.AddField(
            model_name="sitting",
            name="attempt_number",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Which attempt number this sitting represents",
                verbose_name="Attempt Number",
            ),
        ),
    ]
