# Generated by Django 4.2.17 on 2026-05-19 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "school",
            "0003_school_accent_color_school_founded_year_school_motto_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0008_user_division_alter_student_level_and_more"),
        ("core", "0010_term_end_date_term_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Nursery 1", "Nursery 1"),
                            ("Nursery 2", "Nursery 2"),
                            ("KG 1", "KG 1"),
                            ("KG 2", "KG 2"),
                            ("Primary 1", "Primary 1"),
                            ("Primary 2", "Primary 2"),
                            ("Primary 3", "Primary 3"),
                            ("Primary 4", "Primary 4"),
                            ("Primary 5", "Primary 5"),
                            ("Primary 6", "Primary 6"),
                            ("JHS 1", "JHS 1"),
                            ("JHS 2", "JHS 2"),
                            ("JHS 3", "JHS 3"),
                        ],
                        max_length=25,
                    ),
                ),
                ("date", models.DateField()),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes for this session"
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_marked_attendance_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance_sessions",
                        to="school.school",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance_sessions",
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Session",
                "verbose_name_plural": "Attendance Sessions",
                "ordering": ["-date", "level"],
                "unique_together": {("school", "level", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        default="PRESENT",
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional reason for absence/lateness"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="student_attendance.attendancesession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance_records",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": [
                    "student__student__last_name",
                    "student__student__first_name",
                ],
                "unique_together": {("session", "student")},
            },
        ),
    ]
