# Generated by Django 4.2.17 on 2026-01-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="house",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red House"),
                    ("BLUE", "Blue House"),
                    ("GREEN", "Green House"),
                    ("YELLOW", "Yellow House"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_class_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("Primary 1", "Primary 1"),
                    ("Primary 2", "Primary 2"),
                    ("Primary 3", "Primary 3"),
                    ("Primary 4", "Primary 4"),
                    ("Primary 5", "Primary 5"),
                    ("Primary 6", "Primary 6"),
                    ("JHS 1", "JHS 1"),
                    ("JHS 2", "JHS 2"),
                    ("JHS 3", "JHS 3"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
