# Generated by Django 4.2.17 on 2026-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_school_admin",
            field=models.BooleanField(default=False),
        ),
    ]
