# Generated by Django 4.2.17 on 2026-02-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_level',
            field=models.CharField(blank=True, choices=[('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3')], help_text='The class/level this teacher is responsible for (if class teacher)', max_length=25, null=True),
        ),
    ]
