# Generated by Django 4.2.17 on 2026-02-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_assigned_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="division",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nursery", "Nursery/Pre-School"),
                    ("Primary", "Primary School"),
                    ("JHS", "Junior High School"),
                ],
                help_text="The school division this teacher belongs to (Nursery, Primary, or JHS)",
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("Nursery 1", "Nursery 1"),
                    ("Nursery 2", "Nursery 2"),
                    ("KG 1", "KG 1"),
                    ("KG 2", "KG 2"),
                    ("Primary 1", "Primary 1"),
                    ("Primary 2", "Primary 2"),
                    ("Primary 3", "Primary 3"),
                    ("Primary 4", "Primary 4"),
                    ("Primary 5", "Primary 5"),
                    ("Primary 6", "Primary 6"),
                    ("JHS 1", "JHS 1"),
                    ("JHS 2", "JHS 2"),
                    ("JHS 3", "JHS 3"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="assigned_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nursery 1", "Nursery 1"),
                    ("Nursery 2", "Nursery 2"),
                    ("KG 1", "KG 1"),
                    ("KG 2", "KG 2"),
                    ("Primary 1", "Primary 1"),
                    ("Primary 2", "Primary 2"),
                    ("Primary 3", "Primary 3"),
                    ("Primary 4", "Primary 4"),
                    ("Primary 5", "Primary 5"),
                    ("Primary 6", "Primary 6"),
                    ("JHS 1", "JHS 1"),
                    ("JHS 2", "JHS 2"),
                    ("JHS 3", "JHS 3"),
                ],
                help_text="The class/level this teacher is responsible for (if class teacher)",
                max_length=25,
                null=True,
            ),
        ),
    ]
