"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from decouple import config
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY", default="o!ld8nrt4vc*h1zoey*wj48x*q0#ss12h=+zh)kk^6b3aygg=!"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = ["127.0.0.1", "adilmohak1.pythonanywhere.com", "localhost", "127.0.0.1:8000", ".localhost"]

# change the default user models to our custom model
AUTH_USER_MODEL = "accounts.User"

# Application definition

DJANGO_APPS = [
    "modeltranslation",  # Translation
    "jet.dashboard",
    "jet",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Third party apps
THIRD_PARTY_APPS = [
    "crispy_forms",
    "crispy_bootstrap5",
    "django_filters",
]

# Custom apps
PROJECT_APPS = [
    "core.apps.CoreConfig",
    "accounts.apps.AccountsConfig",
    "course.apps.CourseConfig",
    "result.apps.ResultConfig",
    "search.apps.SearchConfig",
    "quiz.apps.QuizConfig",
    "payments.apps.PaymentsConfig",
    "school.apps.SchoolConfig",
    "attendance.apps.AttendanceConfig",
    "fees.apps.FeesConfig",  # Fee management & payment system
    "timetable.apps.TimetableConfig",
    "superadmin.apps.SuperadminConfig",  # Super Admin Portal
    "resources.apps.ResourcesConfig",  # Course learning resources (files, videos)
]

# Combine all apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

# Hosts configuration
ROOT_HOSTCONF = 'config.hosts'
DEFAULT_HOST = 'www'
HOST_SCHEME = 'http'
PARENT_HOST = 'localhost:8000'

MIDDLEWARE = [
    "school.routing_middleware.DomainRoutingMiddleware",  # 🛡️ HOST-BASED ROUTING (Master vs School)
    # "django_hosts.middleware.HostsRequestMiddleware",   # Disabled to use custom routing
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "school.middleware.SchoolMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # whitenoise to serve static files
    # "django_hosts.middleware.HostsResponseMiddleware",  # Disabled
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "school.context_processors.school_context",
                "school.context_processors.tenant_aware_urls",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# https://docs.djangoproject.com/en/stable/ref/settings/#std:setting-DEFAULT_AUTO_FIELD
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/


def gettext(s):
    return s


LANGUAGES = (
    ("en", gettext("English")),
    ("tw", gettext("Twi")),
    ("ga", gettext("Ga")),
    ("ee", gettext("Ewe")),
    ("fr", gettext("French")),
    ("es", gettext("Spanish")),
)

LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"
LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Accra"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# https://docs.djangoproject.com/en/dev/ref/settings/#static-url
STATIC_URL = "/static/"
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#std:setting-STATICFILES_DIRS
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# Media files config
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# -----------------------------------
# E-mail configuration

EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_FROM_ADDRESS = config("EMAIL_FROM_ADDRESS")
EMAIL_USE_SSL = False

# crispy config
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Session configuration
# 30 minutes in seconds
SESSION_COOKIE_AGE = 1800
SESSION_SAVE_EVERY_REQUEST = True

# Strip payment config
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")

# LOGGING
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#logging
# See https://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s "
            "%(process)d %(thread)d %(message)s"
        }
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "root": {"level": "INFO", "handlers": ["console"]},
}

# WhiteNoise configuration
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STUDENT_ID_PREFIX = config("STUDENT_ID_PREFIX", "STU")
TEACHER_ID_PREFIX = config("TEACHER_ID_PREFIX", "TCH")
LECTURER_ID_PREFIX = config("LECTURER_ID_PREFIX", "TEA")


# Constants for Ghana Education System

# Nursery/Pre-school levels
NURSERY_1 = "Nursery 1"
NURSERY_2 = "Nursery 2"
KG_1 = "KG 1"
KG_2 = "KG 2"

# Grade levels for Ghana Basic Education
PRIMARY_1 = "Primary 1"
PRIMARY_2 = "Primary 2"
PRIMARY_3 = "Primary 3"
PRIMARY_4 = "Primary 4"
PRIMARY_5 = "Primary 5"
PRIMARY_6 = "Primary 6"
JHS_1 = "JHS 1"
JHS_2 = "JHS 2"
JHS_3 = "JHS 3"

LEVEL_CHOICES = (
    (NURSERY_1, _("Nursery 1")),
    (NURSERY_2, _("Nursery 2")),
    (KG_1, _("KG 1")),
    (KG_2, _("KG 2")),
    (PRIMARY_1, _("Primary 1")),
    (PRIMARY_2, _("Primary 2")),
    (PRIMARY_3, _("Primary 3")),
    (PRIMARY_4, _("Primary 4")),
    (PRIMARY_5, _("Primary 5")),
    (PRIMARY_6, _("Primary 6")),
    (JHS_1, _("JHS 1")),
    (JHS_2, _("JHS 2")),
    (JHS_3, _("JHS 3")),
)

# Division constants for teacher access control
DIVISION_NURSERY = "Nursery"
DIVISION_PRIMARY = "Primary"
DIVISION_JHS = "JHS"

DIVISION_CHOICES = (
    (DIVISION_NURSERY, _("Nursery/Pre-School")),
    (DIVISION_PRIMARY, _("Primary School")),
    (DIVISION_JHS, _("Junior High School")),
)

# Map each level to its division
DIVISION_LEVEL_MAPPING = {
    DIVISION_NURSERY: [NURSERY_1, NURSERY_2, KG_1, KG_2],
    DIVISION_PRIMARY: [PRIMARY_1, PRIMARY_2, PRIMARY_3, PRIMARY_4, PRIMARY_5, PRIMARY_6],
    DIVISION_JHS: [JHS_1, JHS_2, JHS_3],
}

# Academic terms (Ghana uses 3-term system)
FIRST_TERM = "First"
SECOND_TERM = "Second"
THIRD_TERM = "Third"

TERM_CHOICES = (
    (FIRST_TERM, _("First Term")),
    (SECOND_TERM, _("Second Term")),
    (THIRD_TERM, _("Third Term")),
)

# Keep SEMESTER_CHOICES for backward compatibility, but map to terms
FIRST = "First"
SECOND = "Second"
THIRD = "Third"

SEMESTER_CHOICES = TERM_CHOICES

# Ghana-specific constants
CURRENCY_SYMBOL = "GH₵"
CURRENCY_CODE = "GHS"

# House system colors
HOUSE_CHOICES = (
    ("RED", _("Red House")),
    ("BLUE", _("Blue House")),
    ("GREEN", _("Green House")),
    ("YELLOW", _("Yellow House")),
)
