# Generated by Django 4.2.17 on 2026-01-21 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0001_initial"),
        ("core", "0007_delete_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0007_remove_courseallocation_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Period 1, Break, Assembly", max_length=50
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("LESSON", "Lesson Period"),
                            ("BREAK", "Break Time"),
                            ("ASSEMBLY", "Assembly"),
                            ("MORNING", "Early Morning Class"),
                        ],
                        default="LESSON",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("order", models.IntegerField(help_text="Display order in the day")),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.school"
                    ),
                ),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "ordering": ["school", "order"],
                "unique_together": {("school", "order")},
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Primary 1", "Primary 1"),
                            ("Primary 2", "Primary 2"),
                            ("Primary 3", "Primary 3"),
                            ("Primary 4", "Primary 4"),
                            ("Primary 5", "Primary 5"),
                            ("Primary 6", "Primary 6"),
                            ("JHS 1", "JHS 1"),
                            ("JHS 2", "JHS 2"),
                            ("JHS 3", "JHS 3"),
                        ],
                        help_text="Class level",
                        max_length=25,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "classroom",
                    models.CharField(
                        blank=True, help_text="e.g., Room A, Lab", max_length=50
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Special instructions"),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.period",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.school"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for free periods",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_lecturer": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        help_text="Timetable for specific term",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.term",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Entry",
                "verbose_name_plural": "Timetable Entries",
                "ordering": ["day_of_week", "period__order"],
                "unique_together": {
                    ("school", "term", "level", "day_of_week", "period")
                },
            },
        ),
    ]
