# Generated by Django 4.2.17 on 2026-02-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_custom_domain_school_is_active_and_more'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['school', 'division', 'order'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='period',
            name='division',
            field=models.CharField(blank=True, choices=[('Nursery', 'Nursery/Pre-School'), ('Primary', 'Primary School'), ('JHS', 'Junior High School')], help_text='Academic division this period applies to', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='level',
            field=models.CharField(choices=[('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('KG 1', 'KG 1'), ('KG 2', 'KG 2'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3')], help_text='Class level', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('school', 'division', 'order')},
        ),
    ]
