# Generated by Django 4.2.17 on 2026-02-13 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_school_custom_domain_school_is_active_and_more'),
        ('course', '0009_program_division_program_is_academic_block_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Video Title')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('video', models.FileField(help_text='Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3, webm', upload_to='course_resources/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'wmv', '3gp', 'f4v', 'avi', 'mp3', 'webm'])], verbose_name='Video File')),
                ('thumbnail', models.ImageField(blank=True, help_text='Video thumbnail image (optional)', null=True, upload_to='course_resources/thumbnails/%Y/%m/', verbose_name='Thumbnail')),
                ('description', models.TextField(blank=True, help_text='Brief description of this video', verbose_name='Description')),
                ('duration', models.DurationField(blank=True, help_text='Video duration (auto-detected if possible)', null=True, verbose_name='Duration')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_videos', to='course.course', verbose_name='Course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='School')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Course Video',
                'verbose_name_plural': 'Course Videos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='File Title')),
                ('file', models.FileField(help_text='Valid Files: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip', upload_to='course_resources/files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])], verbose_name='File')),
                ('description', models.TextField(blank=True, help_text='Brief description of this resource', verbose_name='Description')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_files', to='course.course', verbose_name='Course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='School')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Course File',
                'verbose_name_plural': 'Course Files',
                'ordering': ['-upload_time'],
            },
        ),
    ]
