# Generated by Django 4.2.17 on 2026-01-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_activitylog_school_house_school_newsandevents_school_and_more"),
        ("school", "0001_initial"),
        ("accounts", "0004_user_school"),
        ("attendance", "0002_alter_attendance_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancesummary",
            unique_together={("student", "term", "school")},
        ),
        migrations.RemoveField(
            model_name="attendancesummary",
            name="session",
        ),
    ]
