# Generated by Django 4.2.17 on 2026-02-03 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_term_result_released"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0002_school_custom_domain_school_is_active_and_more"),
        ("attendance", "0003_alter_attendancesummary_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Primary 1", "Primary 1"),
                            ("Primary 2", "Primary 2"),
                            ("Primary 3", "Primary 3"),
                            ("Primary 4", "Primary 4"),
                            ("Primary 5", "Primary 5"),
                            ("Primary 6", "Primary 6"),
                            ("JHS 1", "JHS 1"),
                            ("JHS 2", "JHS 2"),
                            ("JHS 3", "JHS 3"),
                        ],
                        max_length=25,
                    ),
                ),
                ("date", models.DateField()),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes for this session"
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.school"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.term"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Session",
                "verbose_name_plural": "Attendance Sessions",
                "ordering": ["-date", "level"],
                "unique_together": {("school", "level", "date")},
            },
        ),
    ]
